const certificates = [
    {
        id: 15,
        title: "Dotnet 8 Web Api",
        description: "Dotnet 8 Web Api",
        image: '/assets/certificates/NET.png',
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
      {
        id: 16,
        title: "Cloud Computing",
        description: "Cloud Computing",
        image: "/assets/certificates/cloud.png",
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
      {
        id: 17,
        title: "Cloud Computing Evidence",
        description: "Cloud Computing Evidence",
        image: "/assets/certificates/Credly.png",
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
      {
        id: 18,
        title: "Design Patterns",
        description: "Design Patterns",
        image: "/assets/certificates/NET.png",
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
      {
        id: 19,
        title: "Docker and Kubernetes",
        description: "Docker and Kubernetes",
        image: "/assets/certificates/Kubernetes.png",
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
      {
        id: 20,
        title: "Docker and Kuberneted Credly",
        description: "Docker and Kubernetes Credly",
        image: "/assets/certificates/KuberNetesCred.png",
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
      {
        id: 21,
        title: "Node js",
        description: "Node js",
        image: "/assets/certificates/Node.png",
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
      {
        id: 22,
        title: "Paralle Programming in Dotnet",
        description: "Parallel Programming in Dotnet",
        image: "/assets/certificates/Parallel.png",
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
      {
        id: 23,
        title: "Software Architecture",
        description: "Software Architecture",
        image: "/assets/certificates/SA.png",
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
      {
        id: 24,
        title: "Service Oriented Architecture",
        description: "Service Oriented Architecture",
        image: "/assets/certificates/SOA.png",
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
      {
        id: 25,
        title: "TypeScript",
        description: "TypeScript",
        image: "/assets/certificates/TS.png",
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
      {
        id: 26,
        title: "React Certificate",
        description: "React Certificate in udemy",
        image: "https://i.ibb.co/JkWMvW6/77085.png",
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
      {
        id: 27,
        title: "HTML & CSS Certificate",
        description: "HTML & CSS Certificate in udemy",
        image: "https://i.ibb.co/HzZNhBp/76975.png",
        tag: ["Certs"],
        gitUrl: "/",
        previewUrl: "/",
      },
]